### PR TITLE
Search results

### PR DESCRIPTION
**Pull request by ivanko22**
Updated according to comments

### CODE REVIEW

**Review by MorganLee909 — CHANGES_REQUESTED** [review]
First, do not delete this pull request like last time. Just make your changes and push it up to GitHub. It is automatically part of this pull request. Don't close and then reopen the pull request.

Just a couple things to change:
Remove all console logs
Address in edit vendor modal shows [object Object]

**Comment by MorganLee909** [comment]
One more thing. Give the toaster a larger z-index in the css. It is blocked by the edit vendor modal.

**Comment by ivanko22** [comment]
updated

**Review by MorganLee909 — CHANGES_REQUESTED** [review]
There are still 3 console logs in the frontend code.
The toaster still appears behind the modal when incorrect data is entered or something goes wrong.

**Comment by MorganLee909** [comment]
The toaster still appears behind the modal when incorrect data is entered or something goes wrong.

**Comment by ivanko22** [comment]
updated

**Comment by MorganLee909** [comment]
Nothing has changed. Why are you not checking this before you commit your code?

**Review by MorganLee909 — APPROVED** [review]
All set

**Pull request merged**
